name: drawappFirebase
description: Drawapp, but with blocs and firebase.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  meta: ^1.0.4
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  rxdart: ^0.19.0
  cloud_firestore: ^0.8.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '1.1.0'
  build_runner: ^1.0.0
  built_value_generator: ^6.1.6
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0

flutter:
  uses-material-design: true
